In [1]:
import numpy as np

# Concatenate 2 array

In [2]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [4]:
b = np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [7]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [8]:
np.concatenate((a,b),axis=0) # Concatenate 2 arrays rowise.

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [9]:
np.concatenate((a,b),axis=1) # Concatenate 2 arrays columnwise

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [11]:
np.concatenate((a,b),axis=None)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
c = np.arange(5,14)
c.shape = (3,3)

In [22]:
c

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [23]:
d = np.arange(1,10)
d.shape = (3,3)

In [24]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
np.concatenate((c,d))

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [26]:
np.concatenate((c,d),axis=1)

array([[ 5,  6,  7,  1,  2,  3],
       [ 8,  9, 10,  4,  5,  6],
       [11, 12, 13,  7,  8,  9]])

# Sorting of array

In [27]:
x = np.array([[10,2,12],[8,7,9],[5,11,13]])
x

array([[10,  2, 12],
       [ 8,  7,  9],
       [ 5, 11, 13]])

In [29]:
x.sort() # sort rows of array
x

array([[ 2, 10, 12],
       [ 7,  8,  9],
       [ 5, 11, 13]])

In [30]:
x.sort(axis = 0) #Sort column of array
x

array([[ 2,  8,  9],
       [ 5, 10, 12],
       [ 7, 11, 13]])

In [31]:
x.sort(axis = 1) #sort rows of array
x

array([[ 2,  8,  9],
       [ 5, 10, 12],
       [ 7, 11, 13]])

In [ ]:
# sorting all elements present in array

In [32]:
x.ravel().sort()
x

array([[ 2,  5,  7],
       [ 8,  9, 10],
       [11, 12, 13]])