In [2]:
import numpy as np

# Creating an array

In [6]:
a = np.arange(1,21)

In [7]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [8]:
a.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [9]:
a.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [10]:
a.reshape(2,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [23]:
a[[0,2,3], : ]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [25]:
a[[3,0,1], : ]

array([[16, 17, 18, 19, 20],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# accessing rows of array 

In [14]:
a = a.reshape(4,5)

In [15]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [16]:
a[0] # accesing 1st row of array.

array([1, 2, 3, 4, 5])

In [17]:
a[2] # accesing 3rd row of array.

array([11, 12, 13, 14, 15])

In [20]:
a[0:2] # accessing more than 1 row of array.

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [21]:
a[1:4:2] # accessing rows by steping of 2.

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])

# accessing random rows of array

In [23]:
a[[0,3], : ] # accessing random rows of array.

array([[ 1,  2,  3,  4,  5],
       [16, 17, 18, 19, 20]])

In [19]:
a[[0,2,3], : ] #accessing 1st, 3rd & 4th row of array.

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [24]:
a[[1,2,-1], : ] # accessing 2nd, 3rd and last row of array.

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

# accessing column of array

In [27]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [31]:
a[:, 2] # accessing 3rd column of array (gives result in 1-D)

array([ 3,  8, 13, 18])

In [32]:
a[:, [2]]  # accessing 3rd column of array (gives result in 2-D)

array([[ 3],
       [ 8],
       [13],
       [18]])

In [39]:
a[:, 0:3] # accessing column start from 1st to last.

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [40]:
a[:, 1:4:2] # accessing column steping by 2.

array([[ 2,  4],
       [ 7,  9],
       [12, 14],
       [17, 19]])

In [42]:
a[:, :4]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

In [45]:
a[:,[0,2,3]] # accessing random column of array.

array([[ 1,  3,  4],
       [ 6,  8,  9],
       [11, 13, 14],
       [16, 18, 19]])

In [46]:
a[:, [4,1,0]] # accessing 5th, 2nd and 1st column of array.

array([[ 5,  2,  1],
       [10,  7,  6],
       [15, 12, 11],
       [20, 17, 16]])

# accessing specific elements from array

In [49]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [48]:
a[1:3,1:3]

array([[ 7,  8],
       [12, 13]])

In [45]:
a[2:,2:4]

array([[13, 14],
       [18, 19]])

In [50]:
a[1,2]

8

In [52]:
a[3,4]

20

In [53]:
a[3,3]

19